name: Create PDF artifact
on: push

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: scientific_data.tex

      - uses: actions/upload-artifact@v2
        with:
          path: scientific_data.pdf
          retention-days: 5
